# Generated by Django 3.1.2 on 2020-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('starting_url', models.CharField(max_length=50)),
                ('next_xpath', models.CharField(max_length=50)),
                ('product_xpath', models.CharField(max_length=50)),
                ('page_query', models.CharField(max_length=50)),
                ('page_steps', models.IntegerField()),
                ('last_page_xpath', models.CharField(max_length=50)),
                ('last_page_arrow', models.CharField(max_length=50)),
                ('search_xpath', models.CharField(max_length=50)),
                ('load_more', models.CharField(max_length=50)),
                ('regex', models.JSONField()),
                ('chunksize', models.IntegerField()),
            ],
        ),
    ]
